project:
  type: website
  output-dir: docs

website:
  title: "Residencia-INE"
  favicon: favicon.ico
  navbar:
    logo: logo_resi.gif
    left:
      - href: index.qmd
        text: "1er. año"
      - href: espacial.qmd  
        text: "2do. año"
    right:
      - icon: building
        href: https://www.ine.gov.ar  

format:
  html:
    theme: 
      light: custom.scss
      dark: [darkly, custom_dark.scss]
    toc: true
    language:
      toc-title-website: "Contenido"
    link-external-icon: false
    link-external-newwindow: true  
    link-external-filter: '^https:\/\/(raw|datos-ine|www)?\.?(linkedin|twitter|github|githubusercontent)\.*'
    code-copy: true
    anchor-sections: false
    bibliography: references.bib



