project:
  type: website
  output-dir: docs

website:
  title: "Residencia-INE"
  navbar:
    left:
      - href: index.qmd
        text: "1er. año"

format:
  html:
    include-in-header: 
      - text: |
          <link rel="icon" type="image/x-icon" href="img/favicon.ico">
    theme: 
      light: [pulse, custom.scss]
      dark: darkly
    toc: true
    language:
      toc-title-website: "Contenido"
    link-external-icon: true
    link-external-newwindow: true  
    link-external-filter: '^https:\/\/(datos-ine|www\.)?(linkedin|twitter|github)\.*'
    code-copy: true
    anchor-sections: false
    bibliography: references.bib



