---
title: "Gestión de datos espaciales con R"
---

<!-- Add icon library -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

### Fundamentación

El análisis espacial constituye una dimensión fundamental en la investigación epidemiológica contemporánea, al permitir la identificación y comprensión de patrones geográficos en la distribución de eventos de salud, sus determinantes y consecuencias. En un contexto donde la disponibilidad de datos georreferenciados en salud es creciente, la incorporación de herramientas analíticas capaces de integrar la dimensión espacial resulta indispensable para la vigilancia y la investigación epidemiológica.

En este marco, el presente taller propone una introducción al manejo de datos espaciales mediante el lenguaje R, abordando tanto aspectos técnicos de gestión y visualización como nociones básicas de geoestadística. La formación en estas competencias técnicas y conceptuales se considera estratégica en el trayecto formativo de las residencias en epidemiología, al fortalecer la capacidad de análisis geoespacial.

 

### Contribución esperada:

La actividad busca incorporar habilidades técnicas vinculadas con la lectura y gestión de datos espaciales, creación de mapas coropléticos y de patrones de puntos, georreferenciación y análisis espacial mediante métodos de interpolación utilizando un software de código abierto como el lenguaje R.

Objetivos:

Se espera que al finalizar este curso los participantes puedan:

- Leer conjuntos de datos espaciales (shape, json, etc) en R.

- Manipular y visualizar datos espaciales creando mapas estáticos e interactivos.

- Georreferenciar puntos a partir de ubicaciones administrativas utilizando conexiones a API gratuitas.

- Comprender e implementar una variedad de técnicas de análisis de datos puntuales, como polígonos de voronoi, densidad de kernel y kriging. 


-	Obtener e interpretar medidas de autocorrelación espacial (*I de Moran*)

### Docente

<p>Christian Ballejo <a href="mailto:cballejo@anlis.gob.ar" class="fa fa-envelope"></a> <a href="https://twitter.com/chrisballejo" target="_blank" class="fa fa-twitter"></a> <a href="https://www.linkedin.com/in/cballejo/" target="_blank" class="fa fa-linkedin"></a> <a href="https://github.com/cballejo/" target="_blank" class="fa fa-github"></a></p>

### Temario

<style type="text/css">
.tg  {border-collapse:collapse;border-color:#aabcfe;border-spacing:0;}
.tg td{background-color:#e8edff;border-bottom-width:1px;border-color:#aabcfe;border-style:solid;border-top-width:1px;
  border-width:0px;color:#669;font-family:Arial, sans-serif;font-size:16px;overflow:hidden;padding:10px 5px;
  word-break:normal;}
.tg th{background-color:#b9c9fe;border-bottom-width:1px;border-color:#aabcfe;border-style:solid;border-top-width:1px;
  border-width:0px;color:#039;font-family:Arial, sans-serif;font-size:16px;font-weight:normal;overflow:hidden;
  padding:10px 5px;word-break:normal;}
.tg .tg-amwm{font-weight:bold;text-align:center;vertical-align:top}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg" style="max-width:900px;margin-left:auto;margin-right:auto"><thead>
  <tr>
    <th class="tg-amwm">Tema</th>
    <th class="tg-amwm">Diapositiva</th>
    <th class="tg-amwm">Práctica</th>
    <th class="tg-amwm">TP</th>
    <th class="tg-amwm">Recursos</th>
  </tr></thead>
<tbody>
  <tr>
    <td class="tg-0lax">Introducción al análisis espacial con R</td>
    <td align="center"><a href="https://datos-ine.github.io/GeoR/01-intro.html" target="_blank">
          <i class="fa fa-laptop  fa-lg"></i></a></td>
    <td align="center"><a href="https://drive.google.com/file/d/1AKUQNCDeb95mLOy350gJSMBTjIq1f7dn/view?usp=sharing" download="Encuentro1.R">
          <i class="fa fa-code fa-lg"></i></font></td>
    <td align="center"><a href="https://drive.google.com/file/d/1twmiJzY3mupKd4zjc1EGvoLmg7hjo9M2/view?usp=sharing" download="TP1.pdf">
          <i class="fa fa-file fa-lg"></i></font></td>      
   <td align="center"><a href="https://gadm.org/">
          <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>
  <tr>
  <td class="tg-0lax">Visualizacion de mapas</td>
  <td align="center"><a href="https://datos-ine.github.io/GeoR/02-mapas.html" target="_blank">
        <i class="fa fa-laptop  fa-lg"></i></a></td>
  <td align="center"><a href="https://drive.google.com/file/d/1lr2ncZDVfoDHaY6i7bir20hI3hVjNMWs/view?usp=sharing" download="Encuentro2.R">
        <i class="fa fa-code fa-lg"></i></font></td>
  <td align="center"><a href="https://drive.google.com/file/d/1wkHcYfO76PUld8XMOb7BY8HSXb5ihxdE/view?usp=sharing" download="TP2.pdf">
        <i class="fa fa-file fa-lg"></i></font></td>      
 <td align="center"><a href="https://cols4all.github.io/cols4all-R">
        <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>
  <tr>
  <td class="tg-0lax">Georreferenciación</td>
  <td align="center"><a href="https://datos-ine.github.io/GeoR/03-georreferenciacion.html" target="_blank">
        <i class="fa fa-laptop  fa-lg"></i></a></td>
  <td align="center"><a href="https://drive.google.com/file/d/1NxbQerSgYNR76hICTAMOhP_h_xts1QFZ/view?usp=sharing" download="Encuentro3.R">
        <i class="fa fa-code fa-lg"></i></font></td>
  <td align="center"><a href="https://drive.google.com/file/d/1tMARp0vJ_5fyux_1ObkRhFOvxpK-FcD6/view?usp=sharing" download="TP3.pdf">
        <i class="fa fa-file fa-lg"></i></font></td>      
 <td align="center"><a href="https://jessecambon.github.io/tidygeocoder/index.html">
        <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>  
  <tr>
  <td class="tg-0lax">Análisis de patrones de puntos</td>
  <td align="center"><a href="https://datos-ine.github.io/GeoR/04-patrones_puntos.html" target="_blank">
        <i class="fa fa-laptop  fa-lg"></i></a></td>
  <td align="center"><a href="https://drive.google.com/file/d/1bz5vBPFkoNy2EEoJQf5uqw0U7knNINCK/view?usp=sharing" download="Encuentro4.R">
        <i class="fa fa-code fa-lg"></i></font></td>
  <td align="center"><a href="https://drive.google.com/file/d/1ahLXj881WMnf7KGqRLg0P0IK2My4y1CE/view?usp=sharing" download="TP4.pdf">
        <i class="fa fa-file fa-lg"></i></font></td>      
 <td align="center"><a href="https://www.gstat.org/gstat.pdf">
        <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>
  <tr>
  <td class="tg-0lax">Análisis espacial</td>
  <td align="center"><a href="https://datos-ine.github.io/GeoR/05-analisis_espacial.html" target="_blank">
        <i class="fa fa-laptop  fa-lg"></i></a></td>
  <td align="center"><a href="https://drive.google.com/file/d/1tsv6X4uQUJYQRaO4MbjmCAZs-zApAiDA/view?usp=sharing" download="Encuentro5.R">
        <i class="fa fa-code fa-lg"></i></font></td>
  <td align="center"><a href="https://drive.google.com/file/d/1PzgVHDmvrcYIQ-_ou9ghwJH9cWtRqjmR/view?usp=sharing" download="TP5.pdf">
        <i class="fa fa-file fa-lg"></i></font></td>      
 <td align="center"><a href="https://rubenfcasal.github.io/estadistica_espacial/kriging.html">
        <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>  
</tbody></table>

### Datos para la practica

Carpeta (para practicas de encuentros) [Datos practicas](https://drive.google.com/file/d/1c_bMWOggqDDqlfskpKdLSOAe6FyUB_V2/view?usp=sharing)

Carpeta (para TP) [Datos TP](https://drive.google.com/file/d/1hxnf3Y6CSTKIU44c3r0jzZWfp_L_5xLM/view?usp=sharing)

Recursos [Fuentes de acceso a información geoespacial](https://drive.google.com/file/d/1qKAOZtTIKmszwku3MsSLiJvCdpL53X3K/view?usp=sharing)

### Bibliografía

[Spatial Statistics for Data Science: Theory and Practice with R](https://www.paulamoraga.com/book-spatial/index.html)

[Geocomputation with R](https://r.geocompx.org/)

[Geospatial Analysis - A Comprehensive Guide - updated Oct 2024](https://www.spatialanalysisonline.com/)

[Spatial Data Science - With Applications in R](https://r-spatial.org/book/)

[Applied Spatial Analysis for Public Health](https://hughst.github.io/)