---
title: "Gestión de datos epidemiológicos con R + RStudio"
---

<!-- Add icon library -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

### Fundamentación

La vigilancia en salud y la investigación epidemiológica son pilares fundamentales para la salud pública, dado que a través de estas se recopilan, analizan e interpretan datos sobre la salud de las poblaciones, permitiendo identificar problemas de salud, evaluar la efectividad de intervenciones y formular políticas públicas basadas en evidencia.

En la actualidad, la generación y acumulación de datos en salud ha crecido exponencialmente, lo que presenta tanto un desafío como una oportunidad. El desafío radica en la capacidad de procesar y analizar grandes volúmenes de datos de manera eficiente y rigurosa, mientras que la oportunidad reside en la posibilidad de extraer información valiosa para mejorar la salud de las poblaciones.

En este contexto, el uso de lenguajes informático-estadísticos se ha vuelto indispensable para los profesionales de la salud pública. R es un lenguaje de programación y entorno de software estadístico gratuito y de código abierto, que ofrece una amplia gama de herramientas para el análisis de datos y la creación de visualizaciones. A su vez, RStudio es un entorno de desarrollo integrado (IDE) para R, que facilita la escritura, ejecución y depuración de código, así como la gestión de proyectos, la colaboración entre investigadores y la producción de documentos científicos y tableros dinámicos soportados por Quarto.

### Contribución esperada:

Incorporar habilidades técnicas vinculadas con el procesamiento de datos, análisis y visualización destinados a la producción de informes técnicos epidemiológicos utilizando un software de código abierto.

Objetivos:

Se espera que al finalizar este curso los participantes puedan:

●   Utilizar R + RStudio para procesar y analizar datos epidemiológicos

●   Aplicar en R y con filosofía tidyverse, metodología estadística en el análisis de datos de salud

●   Producir informes técnicos en diferentes formatos mediante Quarto

### Docente

<p>Christian Ballejo <a href="mailto:cballejo@anlis.gob.ar" class="fa fa-envelope"></a> <a href="https://twitter.com/chrisballejo" target="_blank" class="fa fa-twitter"></a> <a href="https://www.linkedin.com/in/cballejo/" target="_blank" class="fa fa-linkedin"></a> <a href="https://github.com/cballejo/" target="_blank" class="fa fa-github"></a></p>

### Temario

<style type="text/css">
.tg  {border-collapse:collapse;border-color:#aabcfe;border-spacing:0;}
.tg td{background-color:#e8edff;border-bottom-width:1px;border-color:#aabcfe;border-style:solid;border-top-width:1px;
  border-width:0px;color:#669;font-family:Arial, sans-serif;font-size:16px;overflow:hidden;padding:10px 5px;
  word-break:normal;}
.tg th{background-color:#b9c9fe;border-bottom-width:1px;border-color:#aabcfe;border-style:solid;border-top-width:1px;
  border-width:0px;color:#039;font-family:Arial, sans-serif;font-size:16px;font-weight:normal;overflow:hidden;
  padding:10px 5px;word-break:normal;}
.tg .tg-amwm{font-weight:bold;text-align:center;vertical-align:top}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg" style="max-width:900px;margin-left:auto;margin-right:auto"><thead>
  <tr>
    <th class="tg-amwm">Tema</th>
    <th class="tg-amwm">Lectura</th>
    <th class="tg-amwm">Diapositiva</th>
    <th class="tg-amwm">Práctica</th>
    <th class="tg-amwm">Recursos</th>
  </tr></thead>
<tbody>
  <tr>
    <td class="tg-0lax">Bienvenida</td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-book fa-lg"></i></font></td>
    <td align="center"><a href="/primero/diapositivas/00-bienvenida.html" target="_blank">
          <i class="fa fa-laptop  fa-lg"></i></a></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-code fa-lg"></i></font></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>
  <tr>
    <td class="tg-0lax">Datos - Parte 1</td>
    <td align="center"><a href="/primero/clases/00-datos.html">
          <i class="fa fa-book fa-lg"></i></a></td>
    <td align="center"><a href="/primero/diapositivas/01a-datos.html" target="_blank">
          <i class="fa fa-laptop  fa-lg"></i></a></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-code fa-lg"></i></font></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>
  <tr>
    <td class="tg-0lax">Datos - Parte 2</td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-book fa-lg"></i></font></td>
    <td align="center"><a href="/primero/diapositivas/01b-datos.html" target="_blank">
          <i class="fa fa-laptop  fa-lg"></i></a></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-code fa-lg"></i></font></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>
  <tr>
    <td class="tg-0lax">Datos - Parte 3</td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-book fa-lg"></i></font></td>
    <td align="center"><a href="/primero/diapositivas/01c-datos.html" target="_blank">
          <i class="fa fa-laptop  fa-lg"></i></a></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-code fa-lg"></i></font></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>
  <tr>
    <td class="tg-0lax">Lenguaje R</td>
    <td align="center"><a href="/primero/clases/01-introR.html">
          <i class="fa fa-book fa-lg"></i></a></td>
    <td align="center"><a href="/primero/diapositivas/02-analisis.html" target="_blank">
          <i class="fa fa-laptop  fa-lg"></i></a></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-code fa-lg"></i></font></td>
    <td align="center"><a href="https://raw.githubusercontent.com/datos-ine/Residencia-INE/refs/heads/main/primero/recursos/Instalaci%C3%B3n%20del%20software.pdf" download="Instalacion_software.pdf">
          <i class="fa fa-briefcase  fa-lg"></i></a></td>
  </tr>
  <tr>
    <td class="tg-0lax">RStudio</td>
    <td align="center"><a href="/primero/clases/02-introRStudio.html">
          <i class="fa fa-book fa-lg"></i></a></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-laptop  fa-lg"></i></font></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-code fa-lg"></i></font></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>  
    <tr>
    <td class="tg-0lax">Tidyverse</td>
    <td align="center"><a href="/primero/clases/03-introTidy.html">
          <i class="fa fa-book fa-lg"></i></a></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-laptop  fa-lg"></i></font></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-code fa-lg"></i></font></td>
    <td align="center"><a href="/primero/recursos/01-hojaEstilo.html">
          <i class="fa fa-briefcase  fa-lg"></i></a></td>
  </tr> 
  <tr>
    <td class="tg-0lax">Importación y exportación de archivos</td>
    <td align="center"><font color="fafcfc">
         <i class="fa fa-book fa-lg"></i></font></td>
    <td align="center"><a href="/primero/diapositivas/03-lectoescritura.html" target="_blank">
        <i class="fa fa-laptop  fa-lg"></i></a></td>
    <td align="center"><a href="https://github.com/datos-ine/Residencia-INE/raw/refs/heads/main/primero/practicas/01-lectoescritura.zip" download="01-lectoescritura.zip">
          <i class="fa fa-code fa-lg"></i></a></td>
    <td align="center"><a href="/primero/recursos/02-lectura.html">
          <i class="fa fa-briefcase  fa-lg"></i></a></td>
  </tr>
    <tr>
    <td class="tg-0lax">Manipulación de datos</td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-book fa-lg"></i></font></td>
    <td align="center"><a href="/primero/diapositivas/04-gestion.html" target="_blank">
        <i class="fa fa-laptop  fa-lg"></i></a></td>
 <td align="center"><a href=https://drive.google.com/file/d/1wUJAaGKwiWNKsYzIOFFGV18XceEKv4GX/view?usp=sharing">
          <i class="fa fa-code fa-lg"></i></a></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>
  <tr>
    <td class="tg-0lax">Diagnóstico y depuración de datos</td>
    <td align="center"><a href="/primero/clases/06-depuracion.html">
          <i class="fa fa-book fa-lg"></i></a></td>
    <td align="center"><a href="/primero/diapositivas/05a-diagnostico.html" target="_blank">
        <i class="fa fa-laptop  fa-lg"></i></a></td>
     <td align="center"><a href="https://github.com/datos-ine/Residencia-INE/raw/refs/heads/main/primero/practicas/03-diagnostico.zip" download="03-diagnostico.zip">
          <i class="fa fa-code fa-lg"></i></a></td>
    <td align="center"><a href="/primero/clases/05-datosPerdidos.html">
          <i class="fa fa-briefcase  fa-lg"></i></a></td>
  </tr>
  <tr>
    <td class="tg-0lax">Datos ordenados y relacionales</td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-book fa-lg"></i></font></td>
    <td align="center"><a href="/primero/diapositivas/05b-tidy.html" target="_blank">
        <i class="fa fa-laptop  fa-lg"></i></a></td>
     <td align="center"><a href="https://github.com/datos-ine/Residencia-INE/raw/refs/heads/main/primero/practicas/04-tidy.zip" download="04-tidy.zip">
          <i class="fa fa-code fa-lg"></i></a></td>
    <td align="center"><a href="/primero/recursos/06-iteracion.html">
          <i class="fa fa-briefcase  fa-lg"></i></a></td>
  </tr>
  <tr>
    <td class="tg-0lax">Gestión de tipos de datos: caracteres, factores y variables de tiempo</td>
    <td align="center"><a href="/primero/clases/04-tipos.html">
          <i class="fa fa-book fa-lg"></i></a></td>
    <td align="center"><a href="/primero/diapositivas/05c-tipos.html" target="_blank">
        <i class="fa fa-laptop  fa-lg"></i></a></td>
<td align="center"><a href="https://github.com/datos-ine/Residencia-INE/raw/refs/heads/main/primero/practicas/05-tipos.zip" download="05-tipos.zip">
          <i class="fa fa-code fa-lg"></i></a></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>
  <tr>
    <td class="tg-0lax">Análisis Exploratorio de datos - uni y bivariado</td>
    <td align="center"><a href="/primero/recursos/05-resumenes.html">
          <i class="fa fa-book fa-lg"></i></a></td>
    <td align="center"><a href="/primero/diapositivas/06-analisis.html" target="_blank">
    <i class="fa fa-laptop  fa-lg"></i></a></td>
    <td align="center"><a href="https://github.com/datos-ine/Residencia-INE/raw/refs/heads/main/primero/practicas/06-estadisticos.zip" download="06-estadisticos.zip">
          <i class="fa fa-code fa-lg"></i></a></td>
    <td align="center"><a href="/primero/recursos/04-ajusteTasas.html">
          <i class="fa fa-briefcase  fa-lg"></i></a></td>
  </tr>
  <tr>
    <td class="tg-0lax">Visualización de datos</td>
    <td align="center"><a href="/primero/clases/07-visualizacion.html">
          <i class="fa fa-book fa-lg"></i></a></td>
    <td align="center"><a href="/primero/diapositivas/07-visualizacion.html" target="_blank">
    <i class="fa fa-laptop  fa-lg"></i></a></td>
    <td align="center"><a href="https://github.com/datos-ine/Residencia-INE/raw/refs/heads/main/primero/practicas/07-visualizacion.zip" download="07-visualizacion.zip">
          <i class="fa fa-code fa-lg"></i></a></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>
    <tr>
    <td class="tg-0lax">Visualización de datos</td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-book fa-lg"></i></font></td>
    <td align="center"><a href="/primero/practicas/practica_integradora.html" target="_blank">
          <i class="fa fa-laptop  fa-lg"></i></a></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-code fa-lg"></i></font></td>      
    <td align="center"><font color="fafcfc">
          <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>
    <tr>
    <td class="tg-0lax">Comunicar - Documentos Quarto</td>
    <td align="center"><a href="/primero/clases/08-quarto.html">
          <i class="fa fa-book fa-lg"></i></a></td>
    <td align="center"><a href="/primero/diapositivas/08-quarto.html" target="_blank">
    <i class="fa fa-laptop  fa-lg"></i></a></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-code fa-lg"></i></font></td>
    <td align="center"><font color="fafcfc">
          <i class="fa fa-briefcase  fa-lg"></i></font></td>
  </tr>
</tbody></table>

### Prácticas

[Práctico Adolescentes](/primero/practicas/practica_adolescentes.html){target="_blank"}

[Práctico Vigilancia Rita](/primero/practicas/practica_rita.html){target="_blank"}

[Práctico Brote alimentario](/primero/practicas/practica_brote.html){target="_blank"}

### Datos para la practica

Archivo [Diabetes Mellitus](https://drive.google.com/open?id=1HLt_uGKpuO5h6zioDWPb_pZpCatMeVnr)

Archivo [Adolescentes](https://drive.google.com/file/d/1qxYdFKR6jktPjjpzZz9_7f7EN8uiW-Sd/view?usp=drive_link)

Archivo [Vigilancia Rita](https://drive.google.com/file/d/10WVwnr9RVqcb2Mfn06-IdcivP3DEfwNB/view?usp=sharing)

Archivo [Brote](https://drive.google.com/file/d/1p7TUHQiUKW9ve9VkTkk7bDqN6L_FXiEs/view?usp=sharing)


### Bibliografía

[R for Data Science (2e)](https://r4ds.hadley.nz/)

[EpiRhandbook en español](https://epirhandbook.com/es/index.es.html)

[Data Visualization](https://socviz.co/)

[Fundamentos de ciencia de datos con R](https://cdr-book.github.io/index.html)

[Guía de Quarto (en inglés)](https://quarto.org/docs/guide/)