<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Datos ausentes (missing) – Residencia-INE</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e868ba6fad8aeb71849587ff44df17ba.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-7416cfc00a00f4f06d12b98363d5ccde.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-e868ba6fad8aeb71849587ff44df17ba.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="icon" type="image/x-icon" href="favicon.ico">


</head>

<body class="floating nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../logo_resi.gif" alt="" class="navbar-logo light-content">
    <img src="../../logo_resi.gif" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Residencia-INE</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">1er. año</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../espacial.html"> 
<span class="menu-text">2do. año</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.ine.gov.ar"> <i class="bi bi-building" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenidos</h2>
   
  <ul>
  <li><a href="#por-qué-importan-los-datos-ausentes" id="toc-por-qué-importan-los-datos-ausentes" class="nav-link active" data-scroll-target="#por-qué-importan-los-datos-ausentes">¿Por qué importan los datos ausentes?</a></li>
  <li><a href="#contexto-para-la-toma-de-decisiones" id="toc-contexto-para-la-toma-de-decisiones" class="nav-link" data-scroll-target="#contexto-para-la-toma-de-decisiones">Contexto para la toma de decisiones</a></li>
  <li><a href="#mecanismos-de-ausencia" id="toc-mecanismos-de-ausencia" class="nav-link" data-scroll-target="#mecanismos-de-ausencia">Mecanismos de ausencia</a></li>
  <li><a href="#los-na-también-son-información" id="toc-los-na-también-son-información" class="nav-link" data-scroll-target="#los-na-también-son-información">Los NA también son información</a></li>
  <li><a href="#el-error-más-común-eliminar-filas-con-al-menos-un-na" id="toc-el-error-más-común-eliminar-filas-con-al-menos-un-na" class="nav-link" data-scroll-target="#el-error-más-común-eliminar-filas-con-al-menos-un-na">El error más común: eliminar filas con al menos un NA</a></li>
  <li><a href="#limitaciones-de-la-imputación-simple" id="toc-limitaciones-de-la-imputación-simple" class="nav-link" data-scroll-target="#limitaciones-de-la-imputación-simple">Limitaciones de la imputación simple</a></li>
  <li><a href="#métodos-avanzados" id="toc-métodos-avanzados" class="nav-link" data-scroll-target="#métodos-avanzados">Métodos avanzados</a></li>
  <li><a href="#detectar-observaciones-incompletas-en-r" id="toc-detectar-observaciones-incompletas-en-r" class="nav-link" data-scroll-target="#detectar-observaciones-incompletas-en-r">Detectar observaciones incompletas en R</a></li>
  <li><a href="#gestión-de-nas-con-naniar" id="toc-gestión-de-nas-con-naniar" class="nav-link" data-scroll-target="#gestión-de-nas-con-naniar">Gestión de NA’s con naniar</a></li>
  <li><a href="#reemplazo-de-valores" id="toc-reemplazo-de-valores" class="nav-link" data-scroll-target="#reemplazo-de-valores">Reemplazo de valores</a></li>
  <li><a href="#eliminación-de-valores-na" id="toc-eliminación-de-valores-na" class="nav-link" data-scroll-target="#eliminación-de-valores-na">Eliminación de valores NA</a></li>
  <li><a href="#conclusión" id="toc-conclusión" class="nav-link" data-scroll-target="#conclusión">Conclusión</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><strong>Datos ausentes (missing)</strong></h1>
</div>



<div class="quarto-title-meta column-page-right">

    
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/05/missing.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%"></p>
</figure>
</div>
<section id="por-qué-importan-los-datos-ausentes" class="level2">
<h2 data-anchor-id="por-qué-importan-los-datos-ausentes">¿Por qué importan los datos ausentes?</h2>
<p>Cuando trabajamos con datos reales, los valores ausentes o faltantes (conocidos en inglés como <em>missing</em> - <code>NA</code> en R), son más que un inconveniente técnico y lo que hagamos con ellos representan decisiones analíticas con consecuencias concretas sobre la validez de las estimaciones. Ignorarlos o tratarlos de forma descuidada puede introducir sesgo de selección, alterar la representatividad de la muestra e implicar supuestos implícitos sobre el proceso que generó los datos.</p>
<p>Por eso, antes de continuar con el análisis, modelar o graficar, es indispensable entender qué está pasando con los valores ausentes. Tratar los NA no es simplemente “rellenar huecos” u omitirlos sino preguntarse qué dicen esos huecos sobre el proceso que produjo los datos, es decir, si existe un mecanismo de ausencia subyacente.</p>
</section>
<section id="contexto-para-la-toma-de-decisiones" class="level2">
<h2 data-anchor-id="contexto-para-la-toma-de-decisiones">Contexto para la toma de decisiones</h2>
<p>Antes de definir cómo proceder frente a valores ausentes, es necesario contextualizar cada caso y preguntarse por qué esa información no está presente en la tabla de datos.</p>
<p>Un dato aislado rara vez es interpretable por sí mismo, su sentido suele estar anclado en el proceso de recolección y registro. En este punto, los metadatos asociados a la tabla de datos (por ejemplo, el diccionario de datos) resultan fundamentales, ya que permiten evaluar si la ausencia responde a errores de medición o carga —lo que podría justificar su corrección o exclusión, siempre debidamente documentada— o si, por el contrario, es inherente al fenómeno en estudio, en cuyo caso eliminarla implicaría perder información relevante.</p>
<p>La mejor solución para el manejo de datos ausentes es prevenir su aparición. Esto supone fortalecer los procesos de recolección y carga de datos, minimizando la pérdida de información desde el origen.</p>
<p>Sin embargo, en la práctica, con frecuencia no es posible recuperar los datos faltantes. En esos escenarios, nuestro rol como analista consiste en procesar la información disponible y explicitar de manera transparente qué decisiones se adoptaron frente a los valores ausentes y bajo que supuestos.</p>
</section>
<section id="mecanismos-de-ausencia" class="level2">
<h2 data-anchor-id="mecanismos-de-ausencia">Mecanismos de ausencia</h2>
<p>Técnicamente se reconocen tres tipos de mecanismo, con implicancias muy distintas para el análisis:</p>
<p><strong>MCAR — Missing Completely at Random</strong> (ausencia completamente aleatoria)</p>
<p>La probabilidad de que un dato falte no depende ni de las variables observadas ni del valor ausente en sí. El mecanismo es independiente de todo lo demás. Bajo MCAR, eliminar casos con datos faltantes no introduce sesgo en las estimaciones (medias, coeficientes de regresión, etc.), aunque sí reduce el tamaño muestral y la potencia estadística. En la práctica, asumir MCAR es cómodo pero raramente justificado con datos reales.</p>
<p><strong>MAR — Missing at Random</strong> (ausencia dependiente de lo observado)</p>
<p>La ausencia depende de las variables observadas, pero no del valor que falta, una vez que se condiciona en esas variables. En este caso, ignorar el patrón de ausencia y eliminar filas puede introducir sesgo, ya que la estructura de covariables estará desbalanceada entre los casos observados y los ausentes.</p>
<p>Supongamos, por ejemplo, que tenemos la variable <em>nivel de colesterol</em> con valores faltantes y la edad de la persona que está completa. Existe un escenario posible de mecanismo que puede explicarse en que las personas más jóvenes tienen menos probabilidad de hacerse un análisis y ello explica los NA en colesterol.</p>
<p>Entonces en MAR, los datos no están simplemente “faltando al azar” en sentido coloquial, sino “al azar condicionalmente a lo observado”.</p>
<p><strong>MNAR — Missing Not at Random</strong> (ausencia dependiente del valor faltante)</p>
<p>La ausencia depende del propio valor no observado. Es el caso más problemático: no se resuelve con técnicas estándar de imputación. Requiere modelos explícitos del mecanismo de no respuesta, análisis de sensibilidad o información externa.</p>
<p>Un ejemplo para esta situación la tenemos en suponer un estudio poblacional sobre el consumo de alcohol y que parte de los participantes no responda a la pregunta. Es plausible que las personas con consumos más altos tengan mayor probabilidad de no responder (por estigma, deseabilidad social o temor a consecuencias).</p>
</section>
<section id="los-na-también-son-información" class="level2">
<h2 data-anchor-id="los-na-también-son-información">Los NA también son información</h2>
<p>El patrón de ausencia puede ser en sí mismo predictivo. En epidemiología, por ejemplo, el hecho de que un dato no esté registrado rara vez es fortuito y suele ser una señal sistemática asociada a características del paciente, del sistema de registro o del contexto clínico. Crear un indicador binario de “dato faltante” puede capturar mecanismos de comportamiento relevantes como la no respuesta, el abandono o la ocultación deliberada:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> datos <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">edad_na =</span> <span class="fu">is.na</span>(edad))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Este indicador no reemplaza la imputación, pero puede ser útil como variable adicional en modelos o para explorar el mecanismo de ausencia.</p>
</section>
<section id="el-error-más-común-eliminar-filas-con-al-menos-un-na" class="level2">
<h2 data-anchor-id="el-error-más-común-eliminar-filas-con-al-menos-un-na">El error más común: eliminar filas con al menos un NA</h2>
<p>La eliminación masiva de observaciones con datos ausentes es una forma de sesgo de selección.</p>
<p>Cuando una tabla tiene muchos NA, eliminar todas las filas incompletas equivale a redefinir silenciosamente la población de estudio: ya no se trabaja con “todos los individuos”, sino con “los individuos con datos completos”.</p>
<p>Si la completitud de los datos está asociada a variables relevantes, la muestra resultante deja de representar a la población objetivo, y el modelo puede ajustarse a una subpoblación diferente.</p>
<p>Las consecuencias concretas son: alteración de la composición de la muestra, distorsión de las asociaciones estimadas y sesgo en medidas de interés como OR o RR.</p>
<p>Por ejemplo, si los pacientes más graves tienen mayor cantidad de datos ausentes y se los elimina del análisis, se subestima el riesgo real en la población.</p>
</section>
<section id="limitaciones-de-la-imputación-simple" class="level2">
<h2 data-anchor-id="limitaciones-de-la-imputación-simple">Limitaciones de la imputación simple</h2>
<p>Un método frecuente consiste en reemplazar los NA por un valor resumen de la distribución (media o mediana). Sin embargo, la imputación con la media no es “gratuita” sino que modifica la estructura de los datos de manera que reduce artificialmente la variabilidad, debilita las correlaciones entre variables, sesga los coeficientes estimados y genera intervalos de confianza artificialmente estrechos.</p>
<p>En definitiva, se introducen observaciones deterministas que nunca existieron.</p>
</section>
<section id="métodos-avanzados" class="level2">
<h2 data-anchor-id="métodos-avanzados">Métodos avanzados</h2>
<p>La imputación avanzada es un campo extenso que excede los objetivos de esta cursada, pero mencionaremos su existencia. Las técnicas más utilizadas son:</p>
<ul>
<li><p>Imputación múltiple (paquetes de R mice, Amelia): genera varias versiones del conjunto de datos con distintas imputaciones plausibles y combina los resultados mediante reglas estadísticas formales, produciendo estimaciones que incorporan la incertidumbre sobre los valores faltantes.</p></li>
<li><p>Modelos bayesianos: permiten incorporar esa incertidumbre de forma natural dentro del propio modelo de análisis.</p></li>
<li><p>Machine learning: algunos algoritmos (como los basados en árboles -random forest-) manejan NA de forma nativa o mediante imputación por proximidad entre observaciones similares.</p></li>
</ul>
<p>Estos métodos no eliminan la necesidad de reflexionar sobre el mecanismo de ausencia (lo hacen más explícito) y, en algunos casos, permiten modelarlo directamente. Ninguno de ellos es una solución automática y todos requieren decisiones informadas sobre el contexto y los datos.</p>
</section>
<section id="detectar-observaciones-incompletas-en-r" class="level2">
<h2 data-anchor-id="detectar-observaciones-incompletas-en-r">Detectar observaciones incompletas en R</h2>
<p>El lenguaje R gestiona a los datos perdidos mediante el valor especial reservado <code>NA</code> de <strong>Not Available</strong> (No disponible).</p>
<p>En principio, sólo vamos a enfocarnos en como podemos utilizar algunas funciones del lenguaje para detectarlos y contabilizarlos. A partir de su identificación decidiremos que hacer con ellos, dependiendo de su cantidad y extensión, es decir, si los valores faltantes son la mayoría de una variable o la mayoría de una observación o bien si representan la falta de respuesta de una pregunta, con lo cual convenga etiquetarlos.</p>
<p>Una manera de abordar esta tarea con R base para una variables es hacer la sumatoria de valores <code>NA</code>, usando la función de identificación <code>is.na()</code>.</p>
<p>Para ejemplificar, tomamos una tabla de datos de vigilancia con 200 observaciones y 56 variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Cantidad_NA =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(FECHA_FIN_TRAT)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  Cantidad_NA
        &lt;int&gt;
1         142</code></pre>
</div>
</div>
<p>La consulta dice que hay 142 observaciones vacías en la variable FECHA_FIN_TRAT. Lo malo es que debemos hacer esta tarea variable por variable, lo que resulta muy trabajoso.</p>
<p>También la función <code>summary()</code> aplicada sobre el dataframe completo informa la cantidad de <code>NA</code> de variables cuantitativas, lógicas y fecha, pero no lo hace con las de tipo caracter.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(datos)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     SEXO           FECHA_NACIMIENTO              EDAD_DIAGNOSTICO
 Length:200         Min.   :1934-12-13 00:00:00   Min.   : 0.00   
 Class :character   1st Qu.:1973-11-06 12:00:00   1st Qu.:23.00   
 Mode  :character   Median :1989-07-27 00:00:00   Median :33.00   
                    Mean   :1985-12-04 18:14:24   Mean   :37.02   
                    3rd Qu.:1999-11-17 12:00:00   3rd Qu.:49.00   
                    Max.   :2023-05-05 00:00:00   Max.   :88.00   
                                                                  
   GRUPEDAD         PROVINCIA_RESIDENCIA ID_PROV_INDEC_RESIDENCIA
 Length:200         Length:200           Length:200              
 Class :character   Class :character     Class :character        
 Mode  :character   Mode  :character     Mode  :character        
                                                                 
                                                                 
                                                                 
                                                                 
 DEPARTAMENTO_RESIDENCIA ID_DEPTO_INDEC_RESIDENCIA LOCALIDAD_RESIDENCIA
 Length:200              Length:200                Length:200          
 Class :character        Class :character          Class :character    
 Mode  :character        Mode  :character          Mode  :character    
                                                                       
                                                                       
                                                                       
                                                                       
 ESTABLECIMIENTO_SALUD ESTABLECIMIENTO_CARGA PROVINCIA_CARGA   
 Length:200            Length:200            Length:200        
 Class :character      Class :character      Class :character  
 Mode  :character      Mode  :character      Mode  :character  
                                                               
                                                               
                                                               
                                                               
 DEPTO_CARGA        ESTAB_CLINICA      DEPTO_CLINICA          PPL           
 Length:200         Length:200         Length:200         Length:200        
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
                                                                            
 SERVICIO_PENITENCIARIO FECHA_APERTURA               
 Length:200             Min.   :2021-09-20 00:00:00  
 Class :character       1st Qu.:2023-04-12 18:00:00  
 Mode  :character       Median :2023-07-16 00:00:00  
                        Mean   :2023-07-14 09:07:12  
                        3rd Qu.:2023-10-18 12:00:00  
                        Max.   :2024-04-18 00:00:00  
                                                     
 FECHA_NOTIFICACION            MOTIVO_CONSULTA    CLASIFICACION_MANUAL
 Min.   :2023-01-03 00:00:00   Length:200         Length:200          
 1st Qu.:2023-04-03 12:00:00   Class :character   Class :character    
 Median :2023-07-03 00:00:00   Mode  :character   Mode  :character    
 Mean   :2023-07-01 12:36:00                                          
 3rd Qu.:2023-10-03 00:00:00                                          
 Max.   :2023-12-27 00:00:00                                          
                                                                      
 CLASIF_INICIO_TRAT ID_PULMONAR             FIS                     
 Length:200         Length:200         Min.   :2020-12-20 00:00:00  
 Class :character   Class :character   1st Qu.:2023-02-20 00:00:00  
 Mode  :character   Mode  :character   Median :2023-05-12 12:00:00  
                                       Mean   :2023-05-10 05:22:06  
                                       3rd Qu.:2023-08-09 18:00:00  
                                       Max.   :2023-12-21 00:00:00  
                                       NA's   :48                   
 ID_EXTRAPULMONAR   FECHA_INICIO_SINTOMA          RESULTADO_RX      
 Length:200         Min.   :2022-08-15 00:00:00   Length:200        
 Class :character   1st Qu.:2023-03-01 00:00:00   Class :character  
 Mode  :character   Median :2023-05-17 12:00:00   Mode  :character  
                    Mean   :2023-05-28 01:50:46                     
                    3rd Qu.:2023-08-09 00:00:00                     
                    Max.   :2023-12-26 00:00:00                     
                    NA's   :44                                      
 Bacteriologia      Baciloscopia         Cultivo          PRUEBA_RESISTENCIA
 Length:200         Length:200         Length:200         Length:200        
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
                                                                            
 RESISTENCIA           Droga           Tipo_Resistencia  
 Length:200         Length:200         Length:200        
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         
                                                         
 ESTABLECIMIENTO_MUESTRA DEPARTAMENTO_MUESTRA ESTABLECIMIENTO_DIAG
 Length:200              Length:200           Length:200          
 Class :character        Class :character     Class :character    
 Mode  :character        Mode  :character     Mode  :character    
                                                                  
                                                                  
                                                                  
                                                                  
 DEPARTAMENTO_DIAG   Prueba_VIH            VIH           
 Length:200         Length:200         Length:200        
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         
                                                         
 TRATAMIENTO_ANTIRRETROVIRAL Diag_rapido        Resultado_diag_rapido
 Length:200                  Length:200         Length:200           
 Class :character            Class :character   Class :character     
 Mode  :character            Mode  :character   Mode  :character     
                                                                     
                                                                     
                                                                     
                                                                     
   EMBARAZO           DIABETES         CONSUMO_PROB_DROGAS ENF_RESP_CRONICA  
 Length:200         Length:200         Length:200          Length:200        
 Class :character   Class :character   Class :character    Class :character  
 Mode  :character   Mode  :character   Mode  :character    Mode  :character  
                                                                             
                                                                             
                                                                             
                                                                             
    COVID           SE_DECLARA_PUEBLO_INDIGENA  ETNIA        
 Length:200         Length:200                 Mode:logical  
 Class :character   Class :character           NA's:200      
 Mode  :character   Mode  :character                         
                                                             
                                                             
                                                             
                                                             
  TABAQUISMO        ALCOHOLISMO         ESTAB_TTO        
 Length:200         Length:200         Length:200        
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         
                                                         
 FECHA_INICIO_TRAT             FECHA_FIN_TRAT               
 Min.   :2023-01-03 00:00:00   Min.   :2023-03-09 00:00:00  
 1st Qu.:2023-03-20 00:00:00   1st Qu.:2023-08-21 00:00:00  
 Median :2023-07-02 00:00:00   Median :2023-10-23 12:00:00  
 Mean   :2023-06-28 21:42:25   Mean   :2023-10-23 02:04:08  
 3rd Qu.:2023-10-05 00:00:00   3rd Qu.:2024-01-11 12:00:00  
 Max.   :2024-01-08 00:00:00   Max.   :2024-04-05 00:00:00  
 NA's   :43                    NA's   :142                  
 RESULTADO_TRATAMIENTO
 Length:200           
 Class :character     
 Mode  :character     
                      
                      
                      
                      </code></pre>
</div>
</div>
<p>Más completo y en una sola línea la función <code>find_na()</code> del paquete <strong>dlookr</strong> muestra el porcentaje de valores perdidos en todas las variables de una tabla de datos y se complementa con el gráfico de barras de pareto <code>plot_na_pareto()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dlookr)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">find_na</span>(datos, <span class="at">rate =</span> T) <span class="co"># argumento rate = T muestra % de valores NA</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       SEXO            FECHA_NACIMIENTO 
                        0.0                         0.0 
           EDAD_DIAGNOSTICO                    GRUPEDAD 
                        0.0                         0.0 
       PROVINCIA_RESIDENCIA    ID_PROV_INDEC_RESIDENCIA 
                        0.0                         0.0 
    DEPARTAMENTO_RESIDENCIA   ID_DEPTO_INDEC_RESIDENCIA 
                        4.5                         0.0 
       LOCALIDAD_RESIDENCIA       ESTABLECIMIENTO_SALUD 
                        0.0                         0.0 
      ESTABLECIMIENTO_CARGA             PROVINCIA_CARGA 
                        0.0                         0.0 
                DEPTO_CARGA               ESTAB_CLINICA 
                        0.0                        10.0 
              DEPTO_CLINICA                         PPL 
                       10.0                         0.0 
     SERVICIO_PENITENCIARIO              FECHA_APERTURA 
                        0.0                         0.0 
         FECHA_NOTIFICACION             MOTIVO_CONSULTA 
                        0.0                        90.5 
       CLASIFICACION_MANUAL          CLASIF_INICIO_TRAT 
                        0.0                         0.0 
                ID_PULMONAR                         FIS 
                        0.0                        24.0 
           ID_EXTRAPULMONAR        FECHA_INICIO_SINTOMA 
                        0.0                        22.0 
               RESULTADO_RX               Bacteriologia 
                        0.0                         0.0 
               Baciloscopia                     Cultivo 
                        0.0                         0.0 
         PRUEBA_RESISTENCIA                 RESISTENCIA 
                        0.0                         0.0 
                      Droga            Tipo_Resistencia 
                        0.0                         0.0 
    ESTABLECIMIENTO_MUESTRA        DEPARTAMENTO_MUESTRA 
                       36.0                        36.0 
       ESTABLECIMIENTO_DIAG           DEPARTAMENTO_DIAG 
                       38.0                        38.0 
                 Prueba_VIH                         VIH 
                        0.0                         0.0 
TRATAMIENTO_ANTIRRETROVIRAL                 Diag_rapido 
                       99.5                         0.0 
      Resultado_diag_rapido                    EMBARAZO 
                        0.0                         0.0 
                   DIABETES         CONSUMO_PROB_DROGAS 
                        0.0                         0.0 
           ENF_RESP_CRONICA                       COVID 
                        0.0                        99.5 
 SE_DECLARA_PUEBLO_INDIGENA                       ETNIA 
                        0.0                       100.0 
                 TABAQUISMO                 ALCOHOLISMO 
                        0.0                         0.0 
                  ESTAB_TTO           FECHA_INICIO_TRAT 
                       17.5                        21.5 
             FECHA_FIN_TRAT       RESULTADO_TRATAMIENTO 
                       71.0                         0.0 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_na_pareto</span>(datos, </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">only_na =</span> T) <span class="co"># argumento only_na = T muestra variables solo con algún valor NA </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-datosPerdidos_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" style="width:120.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="gestión-de-nas-con-naniar" class="level2">
<h2 data-anchor-id="gestión-de-nas-con-naniar">Gestión de NA’s con naniar</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/05/naniar.PNG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:10.0%"></p>
</figure>
</div>
<p>El paquete <strong>naniar</strong> es un paquete que reúne funciones diseñadas para el manejo de valores ausentes pensado para una gestión completa.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Sus caracteristicas generales son:</p>
<ul>
<li><p>Proporciona funciones analíticas y visuales de detección y gestión</p></li>
<li><p>Es compatible con el mundo “tidy” de tidyverse</p></li>
<li><p>Aborda las relaciones o estructura de la falta de datos.</p></li>
<li><p>Posibilita el trabajo de imputación (no tratado en este curso)</p></li>
</ul>
<p>De las muchas funciones que tiene el paquete seleccionamos algunas para mostrar que son muy útiles para una tarea básica.</p>
<p>La función <code>miss_var_summary()</code> proporciona un resumen sobre los valores NA en cada variable del dataframe similar a <code>find_na()</code> que vimos anterioremente pero con una salida en forma de tabla y un recento absoluto, además de porcentual.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">miss_var_summary</span>(datos)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 56 × 3
   variable                    n_miss pct_miss
   &lt;chr&gt;                        &lt;int&gt;    &lt;num&gt;
 1 ETNIA                          200    100  
 2 TRATAMIENTO_ANTIRRETROVIRAL    199     99.5
 3 COVID                          199     99.5
 4 MOTIVO_CONSULTA                181     90.5
 5 FECHA_FIN_TRAT                 142     71  
 6 ESTABLECIMIENTO_DIAG            76     38  
 7 DEPARTAMENTO_DIAG               76     38  
 8 ESTABLECIMIENTO_MUESTRA         72     36  
 9 DEPARTAMENTO_MUESTRA            72     36  
10 FIS                             48     24  
# ℹ 46 more rows</code></pre>
</div>
</div>
<p>Por el lado gráfico, ofrece la función <code>gg_miss_var()</code> que representa la información de la tabla anterior pero a través de un gráfico <em>lollipop</em> horizontal de tipo <strong>ggplot2</strong>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(datos, </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">show_pct =</span> T) <span class="co"># muestra valores en porcentajes</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-datosPerdidos_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" style="width:120.0%"></p>
</figure>
</div>
</div>
</div>
<p>Hay otra viaulización muy interesante porque muestra las relaciones de los valores ausentes de las variables cuya función se llama <code>gg_miss_upset()</code> y genera un gráfico <strong>Upset</strong> en función de la existencia de valores NA.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_upset</span>(datos) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><img src="img/05/upset1.png" class="img-fluid"> Por defecto, construye el gráfico tomando las primeras 10 variables de la tabla de datos con valores NA de forma decreciente. Esto se puede modificar cambiando el argumentos <code>nset =</code>.</p>
<p>Tiene dos entradas para su lectura. En la parte inferior izquierda nos muestra los nombres de las variables con valores NA ordenadas de menor a mayor medida en una escala absoluta. El gráfico de barras principal, ordenado de forma predeterminada de mayor a menor, informa sobre las cantidades absolutas de valores NA de las combinaciones que aperecen debajo del eje x del gráfico.</p>
<p>Por ejemplo, la variable ETNIA tiene todos sus observaciones como NA y la variable COVID casi lo mismo, mientras que la variable FIS cerca de 50.</p>
<p>Podemos eliminar del gráfico a esas dos variables con casi todos los valores NA, usando formas de tidyverse previas dado que las funciones de naniar son compatibles.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>ETNIA, <span class="sc">-</span>COVID) <span class="sc">|&gt;</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gg_miss_upset</span>() </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><img src="img/05/upset2.png" class="img-fluid"></p>
<p>Al quitar esas dos variables, aparecen dos nuevas con cantidades menores de NA que FIS (FECHA_INICIO_TRAT y FECHA_INICIO_SINTOMA), es decir siguen siendo 10 por defecto.</p>
<p>Si miramos los datos faltantes con estructura notamos que la combinación más frecuente de NA combinados es FECHA_FIN_TRAT, MOTIVO_CONSULTA y TRATAMIENTO_ANTIRETROVIRAL con 39 observaciones a las que le faltan valores en las tres variables simultáneamente.</p>
</section>
<section id="reemplazo-de-valores" class="level2">
<h2 data-anchor-id="reemplazo-de-valores">Reemplazo de valores</h2>
<p>El paquete tiene además dos funciones de reemplazo que funcionan como herramientas antagónicas.</p>
<p><code>replace_with_na()</code> reemplaza valores o etiquetas específicas con valores NA y <code>replace_na_with()</code> hace lo contrario, reemplaza valores NA con valores específicos, como “Sin dato” por ejemplo.</p>
<p>La primera función trabaja sobre el dataframe completo adignando valores NA en la categoría o valor que le indiquemos.</p>
<p>Por ejemplo, la variable ID_PROV_INDEC_RESIDENCIA no tiene valores perdidos pero si hay una categoría/código desconocido (“00”), entonces podemos decirle que ese código sea NA.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Cantidad_NA =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(ID_PROV_INDEC_RESIDENCIA)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  Cantidad_NA
        &lt;int&gt;
1           0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">replace_with_na</span>(<span class="at">replace =</span> <span class="fu">list</span>(<span class="at">ID_PROV_INDEC_RESIDENCIA =</span> <span class="st">"00"</span>)) <span class="sc">|&gt;</span>     </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Cantidad_NA =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(ID_PROV_INDEC_RESIDENCIA)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  Cantidad_NA
        &lt;int&gt;
1           2</code></pre>
</div>
</div>
<p><code>replace_na_with()</code> etiqueta valores faltantes con categorías definidas que serán tenidas en cuenta a la hora de hacer tablas u otras operaciones. Esta función se utiliza dentro de <code>mutate()</code> del tidyverse.</p>
<p>La variable MOTIVO_CONSULTA tiene 181 valores NA que serán etiquetados como “Sin dato” de esta forma:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(MOTIVO_CONSULTA)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  MOTIVO_CONSULTA              n
  &lt;chr&gt;                    &lt;int&gt;
1 Contacto                     2
2 Examen de Salud              1
3 Sintomático Respiratorio    16
4 &lt;NA&gt;                       181</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">MOTIVO_CONSULTA =</span> <span class="fu">replace_na_with</span>(MOTIVO_CONSULTA, </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                                           <span class="st">"Sin dato"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(MOTIVO_CONSULTA)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  MOTIVO_CONSULTA              n
  &lt;chr&gt;                    &lt;int&gt;
1 Contacto                     2
2 Examen de Salud              1
3 Sin dato                   181
4 Sintomático Respiratorio    16</code></pre>
</div>
</div>
</section>
<section id="eliminación-de-valores-na" class="level2">
<h2 data-anchor-id="eliminación-de-valores-na">Eliminación de valores NA</h2>
<p>Cuando decidimos eliminar valores NA de alguna variable, salvo que se quite la variable entera, tenemos que tener en cuenta que perdemos la observación completa, incluso valores válidos que se encuentran en otras variables.</p>
<p>R base tiene una función llamada <code>na.omit()</code> que omite toda observación donde al menos haya un solo NA en alguna variable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">na.omit</span>(datos)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 56
# ℹ 56 variables: SEXO &lt;chr&gt;, FECHA_NACIMIENTO &lt;dttm&gt;, EDAD_DIAGNOSTICO &lt;dbl&gt;,
#   GRUPEDAD &lt;chr&gt;, PROVINCIA_RESIDENCIA &lt;chr&gt;, ID_PROV_INDEC_RESIDENCIA &lt;chr&gt;,
#   DEPARTAMENTO_RESIDENCIA &lt;chr&gt;, ID_DEPTO_INDEC_RESIDENCIA &lt;chr&gt;,
#   LOCALIDAD_RESIDENCIA &lt;chr&gt;, ESTABLECIMIENTO_SALUD &lt;chr&gt;,
#   ESTABLECIMIENTO_CARGA &lt;chr&gt;, PROVINCIA_CARGA &lt;chr&gt;, DEPTO_CARGA &lt;chr&gt;,
#   ESTAB_CLINICA &lt;chr&gt;, DEPTO_CLINICA &lt;chr&gt;, PPL &lt;chr&gt;,
#   SERVICIO_PENITENCIARIO &lt;chr&gt;, FECHA_APERTURA &lt;dttm&gt;, …</code></pre>
</div>
</div>
<p>Aplicar esta función sobre el dataframe datos produce que no quede ninguna observación, dado que vimos que la variable ETNIA tenía sus doscientos valores vacíos.</p>
<p>Una función superadora es <code>drop_na()</code> de tidyr que pertenece a tidyverse, porque omite observaciones que tengan variables que definamos, por ejemplo:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(ETNIA)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 56
# ℹ 56 variables: SEXO &lt;chr&gt;, FECHA_NACIMIENTO &lt;dttm&gt;, EDAD_DIAGNOSTICO &lt;dbl&gt;,
#   GRUPEDAD &lt;chr&gt;, PROVINCIA_RESIDENCIA &lt;chr&gt;, ID_PROV_INDEC_RESIDENCIA &lt;chr&gt;,
#   DEPARTAMENTO_RESIDENCIA &lt;chr&gt;, ID_DEPTO_INDEC_RESIDENCIA &lt;chr&gt;,
#   LOCALIDAD_RESIDENCIA &lt;chr&gt;, ESTABLECIMIENTO_SALUD &lt;chr&gt;,
#   ESTABLECIMIENTO_CARGA &lt;chr&gt;, PROVINCIA_CARGA &lt;chr&gt;, DEPTO_CARGA &lt;chr&gt;,
#   ESTAB_CLINICA &lt;chr&gt;, DEPTO_CLINICA &lt;chr&gt;, PPL &lt;chr&gt;,
#   SERVICIO_PENITENCIARIO &lt;chr&gt;, FECHA_APERTURA &lt;dttm&gt;, …</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(FIS)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 152 × 56
   SEXO  FECHA_NACIMIENTO    EDAD_DIAGNOSTICO GRUPEDAD PROVINCIA_RESIDENCIA
   &lt;chr&gt; &lt;dttm&gt;                         &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;               
 1 M     1948-06-22 00:00:00               74 70-74    Tierra del Fuego    
 2 F     1981-06-20 00:00:00               41 40-44    Buenos Aires        
 3 F     1989-03-30 00:00:00               33 30-34    Buenos Aires        
 4 M     2006-11-17 00:00:00               16 15-19    Chaco               
 5 M     1993-06-02 00:00:00               29 25-29    Jujuy               
 6 M     1989-04-08 00:00:00               33 30-34    Buenos Aires        
 7 F     1977-07-30 00:00:00               45 45-49    Buenos Aires        
 8 F     2008-01-10 00:00:00               15 15-19    Chaco               
 9 M     1987-11-27 00:00:00               35 35-39    Buenos Aires        
10 F     2002-12-21 00:00:00               20 20-24    Buenos Aires        
# ℹ 142 more rows
# ℹ 51 more variables: ID_PROV_INDEC_RESIDENCIA &lt;chr&gt;,
#   DEPARTAMENTO_RESIDENCIA &lt;chr&gt;, ID_DEPTO_INDEC_RESIDENCIA &lt;chr&gt;,
#   LOCALIDAD_RESIDENCIA &lt;chr&gt;, ESTABLECIMIENTO_SALUD &lt;chr&gt;,
#   ESTABLECIMIENTO_CARGA &lt;chr&gt;, PROVINCIA_CARGA &lt;chr&gt;, DEPTO_CARGA &lt;chr&gt;,
#   ESTAB_CLINICA &lt;chr&gt;, DEPTO_CLINICA &lt;chr&gt;, PPL &lt;chr&gt;,
#   SERVICIO_PENITENCIARIO &lt;chr&gt;, FECHA_APERTURA &lt;dttm&gt;, …</code></pre>
</div>
</div>
<p>En el ejemplo anterior aplicamos la función sobre la variable ETNIA y FIS, en el primer caso omite todas las observaciones y en el segundo caso 48 observaciones, mostrando las 152 restantes sin NA en la variable.</p>
<p>Por último, debemos saber que eliminar observaciones por valores faltantes reduce la potencia de cualquier test de hipótesis o modelo que hagamos porque se reduce el tamaño de la muestra.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Acción</th>
<th>Herramienta en R</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cuantificar NA por variable</td>
<td>find_na() (dlookr), miss_var_summary() (naniar)</td>
</tr>
<tr class="even">
<td>Visualizar frecuencia de NA</td>
<td>plot_na_pareto() (dlookr), gg_miss_var() (naniar)</td>
</tr>
<tr class="odd">
<td>Explorar combinaciones de NA</td>
<td>gg_miss_upset() (naniar)</td>
</tr>
<tr class="even">
<td>Recodificar valores como NA</td>
<td>replace_with_na() (naniar)</td>
</tr>
<tr class="odd">
<td>Etiquetar NA como categoría</td>
<td>replace_na_with() (naniar)</td>
</tr>
<tr class="even">
<td>Eliminar observaciones incompletas</td>
<td>drop_na() (tidyr)</td>
</tr>
<tr class="odd">
<td>Justificar y reportar la decisión</td>
<td>—</td>
</tr>
</tbody>
</table>
</section>
<section id="conclusión" class="level2">
<h2 data-anchor-id="conclusión">Conclusión</h2>
<p>No existe un tratamiento <em>“neutro”</em> de los datos ausentes. Cada decisión implica asumir algo sobre cómo se generaron los datos, qué queda dentro del análisis y qué relaciones se están estimando. La transparencia metodológica es parte del rigor analítico, por lo que toda decisión debe tomarse de forma consciente y reportarse explícitamente.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^https:\/\/(raw|datos-ine|www)?\.?(linkedin|twitter|github|githubusercontent)\.*");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>